### PR TITLE
Wpt sensor rebase

### PR DESCRIPTION
**Pull request by JuhaVainio**

### CODE REVIEW

**Comment by JuhaVainio** [comment]
@rakuco Here is the rebase commit

**Comment by rakuco** [comment]
Wow, I didn't know GitHub was so bad at displaying merge commits. I basically can't comment on your commit because GH shows all the upstream changes together with it :/

There are just some formatting issues:
- `tools/wptrunner/wptrunner/executors/actions.py`: `SetSPCTransactionModeAction` is indented incorrectly at the end of the file.
- `resources/testdriver.js`: there is trailing white space after `reset_fedcm_cooldown` and `get_virtual_sensor_information`'s closing `}` character is indented incorrectly.

**Comment by JuhaVainio** [comment]
> Wow, I didn't know GitHub was so bad at displaying merge commits. I basically can't comment on your commit because GH shows all the upstream changes together with it :/
> 
> There are just some formatting issues:
> 
> * `tools/wptrunner/wptrunner/executors/actions.py`: `SetSPCTransactionModeAction` is indented incorrectly at the end of the file.
> * `resources/testdriver.js`: there is trailing white space after `reset_fedcm_cooldown` and `get_virtual_sensor_information`'s closing `}` character is indented incorrectly.

@rakuco https://github.com/JuhaVainio/WPT_sensors/pull/2/commits/5ac97b8605dfa633dd4573063c724e662f3bcac0 fixes this. I only found line number 811 which had trailing spaces in resources/testdriver.js

**Comment by rakuco** [comment]
> * and `get_virtual_sensor_information`'s closing `}` character is indented incorrectly.

This one is in line 908.

> @rakuco [5ac97b8](https://github.com/JuhaVainio/WPT_sensors/commit/5ac97b8605dfa633dd4573063c724e662f3bcac0) fixes this.

Note that you can also just squash these changes into your merge commit if you prefer.

**Comment by JuhaVainio** [comment]
> > * and `get_virtual_sensor_information`'s closing `}` character is indented incorrectly.
> 
> This one is in line 908.
> 
> > @rakuco [5ac97b8](https://github.com/JuhaVainio/WPT_sensors/commit/5ac97b8605dfa633dd4573063c724e662f3bcac0) fixes this.
> 
> Note that you can also just squash these changes into your merge commit if you prefer.

@rakuco: 
Squashed and https://github.com/JuhaVainio/WPT_sensors/blob/10b61cbe835e452f99b502783b19d4ee72ea9c77/resources/testdriver.js#L908 fixed

**Review by rakuco — APPROVED** [review]
lgtm!

**Pull request merged**
